baseURL: https://terrameister.com/
title: Terrameister 2024
canonifyurls: true
theme: Hugo Conference
summaryLength: 30
params:
  FooterText: >-

    <img src="/img/terrameister2024.png" style="width:500px" />

    <br/>

    <a href="https://technative.eu">

    <img src="/images/footer/TechNative_logo_footer.png" />

    </a>

    <br/>

    <br/>

    Het <strong>Terrameister Minecraft Coding Tournement</strong> is een
    initiatief van <a href="https://technative.eu">TechNative B.V.
    Amersfoort</a>.
  Name: Minecraft Coding Tournament
  Date: 2 maart
  Venue: Amersfoort
  City: Amersfoort
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - partners
  Titles:
    about: Info
    location: Locatie
    speakers: Speakers
    schedule: Agenda
    sponsors: Faq
    contact: Contact
    partners: Tutorials
  CallToAction:
    text: Register now!
    link: http://register.example.com
  ForkButton:
    repository: https://github.com/jweslley/hugo-conference/
  Sponsors:
    - name: Hugo
      logo: /img/hugo.png
      url: http://gohugo.io
  Partners:
    - name: Hugo
      logo: /img/hugo.jpg
      url: https://gohugo.io
    - name: BrazilJS
      logo: /img/partner.png
      url: http://braziljs.org
  Schedule:
    - name: Check-in / Breakfast
      time: 9h00
    - name: Linus Torvalds
      photo: /img/speaker.jpg
      bio: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo
      company: Linux Foundation
      link:
        href: http://twitter.com/linus
        text: '@linus'
      presentation:
        title: Digging into a Linux Kernel
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo
        time: 10h00
    - name: Bill Gates
      photo: /img/speaker.jpg
      bio: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo
      company: Microsoft
      link:
        href: http://github.com/billy95
        text: '@billy95'
      presentation:
        title: Introducing Windows 12
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo
        time: 11h00
    - name: Lunch
      time: 12h00
    - name: Chuck Norris
      photo: /img/speaker.jpg
      bio: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo
      company: Delta Command
      link:
        href: http://twitter.com/littlechuck
        text: '@littlechuck'
      presentation:
        title: How to kill a elephant with one finger
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo
        time: 13h00
    - name: Steve Jobs
      photo: /img/speaker.jpg
      bio: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo
      company: Apple, Inc.
      link:
        href: http://github.com/stevie
        text: '@stevie'
      presentation:
        title: Presenting iPad
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo
        time: 14h00
    - name: Coffee-break
      time: 15h00
    - name: Mark Zuckerberg
      photo: /img/speaker.jpg
      bio: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo
      company: Facebook
      link:
        href: http://twitter.com/zuck
        text: '@zuck'
      presentation:
        title: Revealing Facebook Secrets
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo
        time: 16h00
    - name: Steve Wozniak
      photo: /img/speaker.jpg
      bio: >-
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo
      company: Apple, Inc.
      link:
        href: http://twitter.com/woz
        text: '@woz'
      presentation:
        title: Why do I prefer Android over iPhone
        description: >-
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo
        time: 17h00
  menu:
    - disabled: false
      title: Info
      url: /#Info
    - disabled: false
      title: Locatie
      url: /#Locatie
    - disabled: false
      title: Agenda
      url: /#Agenda
    - disabled: true
      title: FAQ
      url: /index.html#Faq
    - disabled: false
      title: Tutorials
      url: /tags/tutorial/
    - disabled: false
      title: Geef je op!
      url: /#geefjeop
